### ISSUE TITLE
Code Review for initial commit

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-output-appsearch#1]
@jsvd First round of code review comments focused on documentation and usage after running the plugin (which works great!). 

I will add more comments as I go:

> Documentation unrelated to section it appears in
https://github.com/logstash-plugins/logstash-output-appsearch/blob/19d434002051624a7a5fb16e460bdb92aa6e02f7/docs/index.asciidoc#L60-L63

> Required flags incorrect
https://github.com/logstash-plugins/logstash-output-appsearch/blob/19d434002051624a7a5fb16e460bdb92aa6e02f7/docs/index.asciidoc#L41-L45

> Could we consider using `host_identifier` to match how the field is represented in appsearch docs, or should it stay as `host` for consistency with other logstash plugins?
https://github.com/logstash-plugins/logstash-output-appsearch/blob/19d434002051624a7a5fb16e460bdb92aa6e02f7/docs/index.asciidoc#L82

> We should consider how we document this - it must be a unique value for each document, otherwise  documents ingested with the same doc id will overwrite any previous documents - stating 'this can be an interpolated value' likely isn't strong enough.
https://github.com/logstash-plugins/logstash-output-appsearch/blob/19d434002051624a7a5fb16e460bdb92aa6e02f7/docs/index.asciidoc#L65-L70

> Could we consider using `timestamp_field` or `timestamp_destination` instead of `store_timestamp` here? I wonder if `store_timestamp` may be implied as a boolean rather than a location for users  not paying careful attention...
https://github.com/logstash-plugins/logstash-output-appsearch/blob/19d434002051624a7a5fb16e460bdb92aa6e02f7/docs/index.asciidoc#L90

**Comment by jsvd** [comment]
> Could we consider using host_identifier to match how the field is represented in appsearch docs, or should it stay as host for consistency with other logstash plugins?

I think host is self explanatory enough without forcing the user to type "identifier", if we see in the future this confuses people we can add the other setting and deprecate host.

> We should consider how we document this - it must be a unique value for each document, otherwise documents ingested with the same doc id will overwrite any previous documents - stating 'this can be an interpolated value' likely isn't strong enough.

This is the same as https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_id, but I added a small sentence to clarify the behaviour. 

> Could we consider using timestamp_field or timestamp_destination instead of store_timestamp here? I wonder if store_timestamp may be implied as a boolean rather than a location for users not paying careful attention...

Agreed, `store_timestamp` is terrible, switching to `timestamp_destination`

**Comment by robbavey** [comment]
What do you think about adding a call to `getEngine` in `register` to verify that `api_key`, `engine` and `host`  are correct before ingesting data?

**Comment by jsvd** [comment]
I've added that check to register + a comment on fields starting with "@"
